name: "Merge Conflicts"

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository == 'jellyfin/jellyfin-web'
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
