name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - id: install-packages
      run: yarn install  --frozen-lockfile
    - id: build
      run: yarn build

  Test:
    runs-on: ubuntu-latest
    steps:
      - id: run-tests
        run: echo "run test suite here"

