name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: install-packages
      run:  npm ci install
    - id: build
      run: npm run build:development
    - id: install-test-dependencies
      run: |
        apt-get install chromium-browser
        npm install chromedriver -g
        npm install https://gitlab.com/gitlab-org/gitlab-selenium-server.git -g
        nohup chromedriver --port=4444 --url-base=wd/hub &
        nohup gitlab-selenium-server &
    - id: run-tests
      run: node tests/testsuite.js
