name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

cache:
  paths:
    - node_modules/
    - .yarn


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - id: set-cache
      run: yarn config set cache-folder .yarn
    - id: install-packages
      run: yarn install
    - id: build
      run: yarn build

  Test:
    runs-on: ubuntu-latest
    steps:
      - id: set-cache
        run: yarn config set cache-folder .yarn
      - id: run-tests
        run: echo "run test suite here"

