name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - id: install-packages
      run: yarn install
      working-directory: ./
    - id: build
      run: yarn build
      working-directory: ./

  Test:
    runs-on: ubuntu-latest
    steps:
      - id: run-tests
        run: echo "run test suite here"

