name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: test
      run: |
        pwd
        ls -la
    - id: install-packages
      run: yarn install  --frozen-lockfile
    - id: build
      run: yarn build:development
    - id: run-tests
      run: echo "run test suite here"

