name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: test
      run: |
        pwd
        ls -la
    - id: install-packages
      run:  |
        npm ci install
        npm ci install selenium-webdriver
    - id: build
      run: npm run build:development
    - id: run-tests
      run: npm tests/testsuite.js
