name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  
jobs:
  Build:
    stage: build
    tags:
      - node
    before_script: 
      - yarn config set cache-folder .yarn
      - yarn install 
    script:
      - yarn build

  Test:
    stage: test
    tags:
    - node
    before_script: 
      - yarn config set cache-folder .yarn
    script:
      -echo "run test suite here"

