name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

jobs:
  Build:
    stage: build
      steps:
        - yarn config set cache-folder .yarn
        - yarn install 
        - yarn build

  Test:
    stage: test
      steps:
        - yarn config set cache-folder .yarn
        - echo "run test suite here"

